name: HTML Code Tests

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: Install dependencies
        run: npm install htmlhint

      - name: Run HTMLHint tests
        run: npx htmlhint path/to/your/html/files
